apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    system: orders
spec:
  selector:
    app: payments
  type: LoadBalancer
  ports:
  - port: 50053
    targetPort: 50053
    protocol: TCP
