apiVersion: v1
kind: Service
metadata:
  name: reservations
  labels:
    system: orders
spec:
  selector:
    app: reservations
  type: LoadBalancer
  ports:
  - port: 50052
    targetPort: 50052
    protocol: TCP
